// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {node} from '../models';

export function ChromeDownloadURL():Promise<string>;

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetDeviceID():Promise<string>;

export function GetLogPath():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function GetStatus():Promise<node.Status>;

export function GetVersion():Promise<string>;

export function IsChromeInstalled():Promise<boolean>;

export function OpenLogsFolder():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function ShowWindow():Promise<void>;

export function Toggle():Promise<boolean>;
