// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChromeDownloadURL() {
  return window['go']['main']['App']['ChromeDownloadURL']();
}

export function ConfirmSignUp(arg1, arg2) {
  return window['go']['main']['App']['ConfirmSignUp'](arg1, arg2);
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetDeviceID() {
  return window['go']['main']['App']['GetDeviceID']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsChromeInstalled() {
  return window['go']['main']['App']['IsChromeInstalled']();
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ResendSignUpCode(arg1) {
  return window['go']['main']['App']['ResendSignUpCode'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SignIn(arg1, arg2) {
  return window['go']['main']['App']['SignIn'](arg1, arg2);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function SignUp(arg1, arg2) {
  return window['go']['main']['App']['SignUp'](arg1, arg2);
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}
